### ISSUE TITLE
"Save questionnaire in browser" button on voting page

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1015]
On the student voting page a button on the bottom should save the user's questionnaire data in the browser cache (via Sisyphus, is already done automatically every few seconds) and tell the user that the evaluation can be continued by reopening the page. A tooltip in the button should explain that the evaluation has to be continued in the same browser on the same device.
The button text should be changed to 'Saved' or similar and return to the previous text a few seconds later (see Feedback button in page footer).
ref #355

**Comment by janno42** [comment]
The mentioned tooltip and confirmation should be added.

**Comment by felixrindt** [comment]
Sorry @He3lixxx , but I referenced the wrong issue in the PR you just merged. It fixed this issue, so #1015 can be closed. ¯\_(ツ)_/¯

**Comment by He3lixxx** [comment]
Fixed in #1077
