### ISSUE TITLE
Insert quick rating possibility in the last reminder email

### ISSUE THREAD

**Issue by He3lixxx** [fsr-itse/EvaP#1045]
This requires #1044

Users suggested that we insert the final rating question in the last reminder email, so users who don't want to go to the page and do a full evaluation can at least rate the course.
There is some discussion necessary:
- Do we want users who rated a course this way to receive rewards for the semester?
- Do we want to count the answer for this one question like a whole evaluation?

This could also be useful for small courses where the evaluation consists of only one question.

**Comment by janno42** [comment]
we decided not to add these one question votes. our participation rate is really good and the most valuable feedback comes from the text answers. a single voting question for an overall grade doesn't really add to the data value of the evaluation and might even allure some students not to do the full evaluation who would have done it if we don't offer this quick solution.
