### ISSUE TITLE
Bootstrap css class name mismatch: collapse vs collapsed

### ISSUE THREAD

**Issue by He3lixxx** [fsr-itse/EvaP#1051]
In [evap.scss:561](https://github.com/fsr-itse/EvaP/blob/master/evap/static/css/evap.scss#L561) we are using `collapsed` as css class to render the rotating arrow that indicates whether the `collapse-toggle` is collapsed or shown.
In [Bootstrap's documentation](https://v4-alpha.getbootstrap.com/components/collapse/) it says that `collapse` is the correct class to use when the content is hidden.
Therefore, we should draw the `hidden`-arrow on `collapse`, not on `collapsed`.

**Comment by janno42** [comment]
Actually the `collapse` class is set for the element that is hidden after collapsing. Bootstrap does not set any class to the toggle element based on the state. So I would suggest keeping `collapsed` for those to prevent class name collisions.
