### ISSUE TITLE
Direct delegation

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1062]
Responsibles should see a button next to each course on their index page that allows them to delegate the preparation of this course to another user. This button should open a selection field (e.g. in a modal) where the user can be specified. Submitting this would then add the selected user as an editor to the course and optionally send a message to the user, informing about the delegation.

**Comment by karyon** [comment]
for the protocol: #162

**Comment by janno42** [comment]
good catch - i though we had something like that before but only looked in the open issues :)

**Comment by janno42** [comment]
see also https://github.com/fsr-itse/EvaP/wiki/Feature-Ideas

**Comment by He3lixxx** [comment]
- The direct delegation button shall only be shown if there are no editors for this course that are not responsible
- When the user selects a delegate and clicks the button, this shall send a post request (submit the form). There should now be a contribution of this user where can_edit is true. The page should then be reloaded. The button should not be there anymore, see 1. There should be a message on top of the page (use django messages framework) indicating that this user was added as editor and sent an email with further information.
- The email that is sent should be derived from an email template to the selected user, copy to responsible and his delegates and cc_users. There should be a migration for this template (empty template created). 
- When the modal is opened, no user shall be selected and the submit button shall be disabled. It shall be enabled when a user is selected.
- Inactive users are no choices in the selection field
