### ISSUE TITLE
Check MEDIA_URL setting

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#1065]
We need MEDIA_ROOT since files are uploaded for importing, and also grades. the former are not downloaded at all, the latter are downloaded only via sendfiles.

Therefore we probably don't need the MEDIA_URL setting, since no files are directly downloaded. We probably also don't need [this code in the urls.py](https://github.com/fsr-itse/EvaP/blob/master/evap/urls.py#L23). If we do, it should be [updated](https://docs.djangoproject.com/en/2.0/howto/static-files/#serving-files-uploaded-by-a-user-during-development).

**Comment by janno42** [comment]
The `MEDIA_URL` is currently used when editing an already uploaded grade document. The file field in the form shows the uploaded file with a direct link.
So what do you suggest?

**Comment by karyon** [comment]
summary of our discussion:

the direct link is not good since it circumvents django permission checking and lets everyone download the grade documents.

on production, that part of the server config was disabled for quite some time.

we should probably make this a django view, the only question is how to put that into a form field.

and then we probably do not need the MEDIA_URL setting.

**Comment by karyon** [comment]
the easiest way is probably to override the template of the widget and let that template use the url to our view.

the underlying problem is that the default widget for FileFields is the ClearableFileInput widget, which renders a url using the MEDIA_URL setting (at least it looks like that to me). we are not using MEDIA_URL but instead our views with django-sendfile.

one could use some mod_wsgi configuration to use MEDIA_URL and let apache and mod_wsgi do the authorization, but i'm not sure how that would work during development without apache and we can simply stick to the existing solution instead.
