### ISSUE TITLE
Missing navbar cache refresh on user group change

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#1066]
The navbar is cached per user and per language: https://github.com/fsr-itse/EvaP/blob/master/evap/evaluation/templates/base.html#L38

When changing the the permissions of users (e.g. making them grade uploaders or staff members), and they have visited the site in the hour before, it might take up to an hour for them to see the changes.

Also, same happens when the first course of a new semester is published. that's a rather unlikely case, but then again, it should be just one line to fix it.

Also, when doing the course import for a semester, the navbar cache should be reset for all users, and when saving a course, for all its participants and contributors.

ref #733

**Comment by janno42** [comment]
we don't need to clear the cache when the first course of a new semester is published, because all results will soon be shown on a single results page. staff users and grade publishers are the only users who see semesters in the navbar - for those users the cache was refreshed on semester creation.
