### ISSUE TITLE
Scrolling with a dragged item does not work

### ISSUE THREAD

**Issue by He3lixxx** [fsr-itse/EvaP#1078]
For example on:
- staff questionnaires edit page
- contributor edit formset (course edit page)
- staff questionnaire edit page
- faq sections
- faq questions
- degrees

If you drag an item, you can not scroll while you have it dragged. Tested with firefox 57.0.3 and Chrome 63.0.3239.132

**Comment by janno42** [comment]
closed by https://github.com/fsr-itse/EvaP/pull/1098
