### ISSUE TITLE
Don't highlight default button when hovering over a different one

### ISSUE THREAD

**Issue by He3lixxx** [fsr-itse/EvaP#1080]
(Issue applies only after #1072 was merged)

Currently, introduced with highlighting the whole row when hovering, the default action for the row is highlighted. The highlighting doesn't go away then the user hovers any other button. This may be confusing, so removing the highlighting in this case would be nice.

This might apply to any page that has the full row highlighting feature. These include the contributor index page, the participant index page and the semester results page.

From what we know at the moment, this requires javascript and cannot be done with plain css.

**Comment by janno42** [comment]
fixed in 028b6301
