### ISSUE TITLE
Continuous text answer review

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1094]
When reviewing text answers, it should be possible to faster approve individual answers. Currently two ideas exist for the reviewing UI:
- Either approved answers are removed so that the next answer and its yes and no buttons move up to the exact same position where the old answer was. This allows to approve answers without moving the mouse every time.
- Another possibility (which would be even better) is to only show a single text answer at a time and to approve/hide it by pressing a key on the keyboard. After each choice the next answer is shown.

Additionally, after all text answers for a course have been reviewed, it should be possible to easily switch to the next course (e.g. navigation button to "next course" or another hotkey).

**Comment by karyon** [comment]
@janno42, @pixunil you guys keep in mind that #1130 needs to be integrated somehow?
