### ISSUE TITLE
Set Course.last_modified_user only when saving the course form

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#1097]
Course.`last_modified_user` should only be set if some user edits the course through the course edit form. At the same time, the `last_modified_time` should be set manually to the current time.

Currently, `helper_semester_course_operation_start` sets the last_modified_time but not the user, but it should set neither. `update_courses` sets both, but should set neither. The `cronjob_user` is used for that, it can be removed completely (basically, create a migration that reverts `0053_create_cronjob_user.py`). `last_modified_time` is currently set automatically by django (`auto_now=True`), this would need to be changed.

This will partly revert https://github.com/fsr-itse/EvaP/pull/845. Rationale: According to @janno42, the `last_modified_user` is used to determine who to talk to in case of questions. If some staff user changes the state of a course that's of no interest, and the cronjob user is not helping at all in that regard.

**Comment by janno42** [comment]
Currently the last modified user isn't changed when only contributions are changed. It should also be set then.
Whenever information in the course form is changed (via "save" or "save and approve"), the information should be updated. if "save and approve" does not make changes except the approval, the information should not be changed.
