### ISSUE TITLE
Consider longer session timeout 

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#1101]
Right now, sessions expire after [the default duration of two weeks](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-SESSION_COOKIE_AGE). We should consider setting that to several months so users need to login less often.

**Comment by He3lixxx** [comment]
Also, we should consider increasing the expiration for the current session either at every request or when you visit the vote page. I just tried on my machine and my session did not get renewed, so in case I log in, then wait 13.9 days and then start a vote, I might have a invalid session by the time i want to submit my vote.

If we do this, we have to decide whether we want to ask for a password before the session renewal, so  a hijacked session doesn't grant you infinite access to an account.

However, if we just decide that using HTTPS should be enough protection against session hijacking, we might increase the default timeout and add renewal, I don't see any negative aspects then. If someone manages to break SSL, we have bigger problems anyway.

**Comment by karyon** [comment]
as per the discussion, lets set the session timeout to a year. HTTPS is enough protection.

the sessions are not renewed automatically, we would need to do that as well. simplest solution would be to set [SESSION_SAVE_EVERY_REQUEST](https://docs.djangoproject.com/en/2.0/ref/settings/#session-save-every-request), but maybe we find something that does not imply additional database hits on every request.
