### ISSUE TITLE
Investigate a proper caching backend like redis

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#1102]
Right now, we're using the [database backend](https://github.com/fsr-itse/EvaP/blob/master/evap/settings.py#L101) for the cache. We should test using [django-redis](https://github.com/niwinz/django-redis), how much page loading time that saves (if at all), and balance that against the setup and maintenance cost.

What would move to redis is the cache itself as well as the [session engine](https://docs.djangoproject.com/en/dev/ref/settings/#session-engine)

Compared to redis, the alternative [memcached](https://docs.djangoproject.com/en/2.0/topics/cache/#memcached) is supported natively by django, but offers no persistence, i.e. in case of a server restart the cached data including sessions would be lost. That's not that bad and we should try that out if redis is e.g. too much of a hassle to setup.

**Comment by karyon** [comment]
the setup of redis is dead simple and no issue at all. We need to decide primarily on

* whether we want this on production
* if yes, whether we want this by default in the settings.py of the repo
  * alternatively, just in the vagrant vm

Actually, the options are really to either use it everywhere or not use it at all. If we use it somewhere but not everywhere, the code cannot rely on e.g. the cache being fast. If the code cannot rely on it, there will be no page that loads significantly faster with redis, and then it's probably not worthwhile to use it at all.

A note on loading speed of the results page:
* If we want to cache per course, we need to use redis, the database is too slow. Caching per course makes the code much simpler.
* Alternatively, I implemented putting one large dictionary with one key per course into the cache. This is very fast even without redis, even faster than caching per course with redis, but adds some code complexity for dealing with that dictionary.

**Comment by He3lixxx** [comment]
Both me and @janno42 agreed that we want to use redis.
