### ISSUE TITLE
Misguiding messages on contributor's course edit page

### ISSUE THREAD

**Issue by He3lixxx** [fsr-itse/EvaP#1124]
When a course is already approved, the contributor course edit page shows a message saying you can't edit this course anymore (introduced in #1076).
Also, a message instructing the user to edit the data is shown. This is misleading. The second message shouldn't be there.

![grafik](https://user-images.githubusercontent.com/13838962/37304966-601f88f0-2633-11e8-8ca8-e49b3c07dc29.png)

@janno42 please make sure I'm not missing out anything here.

**Comment by janno42** [comment]
Correct, this message should be removed for courses already approved by an editor.
