### ISSUE TITLE
Additional private text answers

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1131]
Under each text answer for a contributor a button will be added that adds an additional text box. This text box enables users to submit an additional private text answer that will only be shown to this contributor (and to reviewers) and not to the responsible person or any other people (like text answers marked as private during review).

For review purposes (to prevent one user spamming the same answer over and over) text answers need to be grouped by user (see #1130).

**Comment by chrisma** [comment]
I would appreciate it if the UI for evaluation would make it clear which fields are viewable by which parties.

For the current field "Kommentare zur Person / Personal Feedback", which is viewable not only by the contributor themselves, but also by other people responsible for the course, it would maybe also be helpful to know who those other people are. For example, a small help text with `This feedback is only visible to <contributor_name> as well as <administrator_name> and <prof_name>`.

Intuitively, I assumed the current implementation already worked like the feature described in this ticket, i.e. that "personal feedback" would be viewable only by the person in question.

The additional private text answer possibility of this ticket should then make it clear to the user evaluating that this feedback is only viewable by the person in question.

**Comment by janno42** [comment]
For comment visibility see #1133.

**Comment by karyon** [comment]
Now that all text answers for contributors are private... @janno42 i think we don't need this issue here anymore?

**Comment by janno42** [comment]
Text answers for contributors are not all private, but after the changes in #1279 they can only be seen by the contributors themselves, their delegates and the review team; responsible contributors can't see the text answers about other people anymore.
