### ISSUE TITLE
Test failure depending on time of day

### ISSUE THREAD

**Issue by He3lixxx** [fsr-itse/EvaP#1142]
We currently have 4 tests that fail if your system time is between 00:00 and 00:00 + EVALUATION_END_OFFSET_HOURS:

- evap.evaluation.tests.test_models.TestCourses:test_evaluation_ended
- evap.evaluation.tests.test_models.TestCourses:test_in_evaluation_to_evalued
- evap.evaluation.tests.test_models.TestCourses:test_in_evaluation_to_published
- evap.evaluation.tests.test_models.TestCourses:test_in_evaluation_to_reviewed

**Comment by felixrindt** [comment]
I'll work on this now.
