### ISSUE TITLE
Proportional rewards

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1151]
Students should get a reward even if they missed an evaluation to still motivate them to finish the other evaluations.

- Once students have evaluated all courses they participated in, they receive `REWARD_POINTS_FULLY_EVALUATED` (default: 3) reward points (already implemented, setting is currently called `REWARD_POINTS_PER_SEMESTER`).
- If students didn't evaluate all their courses, they can still receive reward points once for all courses they participated in either the evaluation period ended or they already submitted their evaluation for the course.
    - They receive `REWARD_POINTS_TWO_THIRDS` (default: 2) reward points if they evaluated at least 66% of their courses.
    - They receive `REWARD_POINTS_ONE_THIRD` (default: 1) reward points if they evaluated at least 33% of their courses.

**Comment by karyon** [comment]
so, basically, `floor(evaluated_courses / total_courses * REWARD_POINTS_PER_SEMESTER)`?

if anything more elaborate is needed, i would propose something like `round(evaluated_courses / total_courses * REWARD_POINTS_PER_SEMESTER) + BONUS_WHEN_FULLY_EVALUATED`, gradually giving more points for more evaluated courses and a bonus for 100%ing the evaluation, or, for total freedom, a list of tuples like
```
# list of (fraction, points): when user evaluaties `fraction` of their courses, they get `points` points
REWARD_POINTS = [
    (1.0/3.0, 1), 
    (2.0/3.0, 2), 
    (3.0/3.0, 3), 
]
```
so the user can do whatever they want to do. having exactly three tiers seems both restricted and a bit arbitrary to me. it's not really simpler for the user and also not simpler in the code.

**Comment by janno42** [comment]
tuples are a perfectly customizable solution 👍
