### ISSUE TITLE
Personal result export

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1160]
On each user profile page the list "Courses contributing to (active semester)" should be extended to hold all courses the user is contributing to, grouped by semester (current semester on top). Each entry has an "Personal export" button that links to this course's results page where
- individual cards for all other contributors are not shown (only collapsing is not sufficient because in some situations we have more than 20 contributors and the card headers would still use up too much space) and
- only text answers which are visible for this user are shown.

This helps to export results for a user as PDF on request. The buttons linking to the personal export view could also be added on the contributor index page.

**Comment by karyon** [comment]
I would expect this to be easily accessible by the contributors themselves.

Of course we can give staff users access to this, but is that really necessary? I'm not directly opposed to that, but would like to avoid to make an "output all information about a user"-feature accessible for more people than necessary. For external users, whose accounts are disabled rather quickly, this might be necessary, but for internal users I think it's perfectly reasonable for staff users to tell them "in your menu, click that button" or "click this link here and login".

Of course this would require this page to look ok when printing/exporting to pdf out of the box without additional work, but that would be nice in any case.

**Comment by janno42** [comment]
The results pages should already be optimized for printing. I would expect this feature to just provide links to all relevant results pages which are displayed a little bit filtered as described.

**Comment by janno42** [comment]
The same filtered result view could also be provided to the contributors as a "personal printing view".

**Comment by LeaGe** [comment]
Other contributors should be shown (e.g. in a comma-separated list)

**Comment by janno42** [comment]
Make sure not to allow non-staff users to view filtered views for other users.

**Comment by janno42** [comment]
For contributors there should be three options in the then called "View" switch button on the top right of a course's results page:
- `Filtered` shows the filtered view for personal export. The tooltip should explain that "This filtered view is meant for export and shows only your personal results as well as those about the course. Other contributors' results and your private answers are hidden."
- `Full` is the former `Myself` view and shows everything the user can see.
- `Public` (or `Participants` for private courses) is the same view as before and displays only the results all internal users (or all participants in case of private courses) can see.

Staff users will usually have only the two options `Full` and `Public`. Only when they are accessing a filtered results page from a contributor's user profile, the option `Filtered` should be added and marked active.
