### ISSUE TITLE
Easier deletion of old grade documents

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#1193]
We decided to change the way we're dealing with grade documents. As they aren't needed anymore after about a year, they can completely be removed from the server by a staff operation.

The current `SemesterGradeDownloadActivation` should be removed and instead a button `Delete all grade documents` should be added to the staff semester page. After confirming the deletion, all `GradeDocument`s for the respective semester and all the files they point to are deleted.

**Comment by karyon** [comment]
in some cases where the use of `are_grades_activated` cannot be simply removed, it can be replaced by checking whether there are any grade documents for that semester.
