### ISSUE TITLE
Results page rendering bug with Firefox

### ISSUE THREAD

**Issue by He3lixxx** [fsr-itse/EvaP#1233]
If you have a lot of courses (how many depends on the performance of your computer, we think?) and render the results page, it might occurr that firefox closes the card body way too early and renders the footer right below, while there are still courses, that then overflow:

![image](https://user-images.githubusercontent.com/13838962/43204990-a00dca40-9022-11e8-8eab-25f8e18b577b.png)

Triggering some kind of re-calculation on the results table fixes this for the current page load, e.g. if you inspect the card body. This looks very much like a browser bug to me. I tried to put some javascript in the page to autmatically re-render the table and fix this on every page load, but it doesn't really work. (see https://github.com/He3lixxx/EvaP/commit/c72e734fdda2e377abe165d30fa0d23fe1726072)

This is pretty much a show-stopper currently.

Edit: Open questions that might lead us to a fix or a minimal bug example for firefox:
- Does with happen without the datatables stuff?
- Does this happen if we remove our css?

**Comment by janno42** [comment]
- it also happens without activating datatable

i tried several things, it's getting better, but my latest attempt also doesn't work (https://github.com/janno42/EvaP/commit/eb5b1550ce6f71869b13f3684024ac8516261421)

**Comment by janno42** [comment]
the error still occurs when removing the flexboxes (https://github.com/janno42/EvaP/commit/be1eda75d57f14eaa5acd4c717e0fe7789ff96de).
it's getting better though, because the card is now rendered correctly and the footer only seems to be misplaced when scrolling before the page loaded completely.
