### ISSUE TITLE
Participant count incorrect on results index

### ISSUE THREAD

**Issue by Steditor** [fsr-itse/EvaP#1248]
E.g. for "Lehrerworkshop bei der Endrunde des Bundeswettbewerb Informatik (Sommersemester 2017)" the overview shows "0/0", or for MINT-Camps it says "1/1" or "3/3" participants - the correct numbers are 12, 24 and 22.

![capture](https://user-images.githubusercontent.com/2188983/43835155-2096edf6-9b11-11e8-98ea-b6f8e62231fa.PNG)

**Comment by janno42** [comment]
The mentioned MINT-Camps aren't private courses, so this is a general issue.
When caching the results, `participants` and `voters` are counted, which is correct when publishing for the first time, but not when recalculating the cache later on. Some users might have already been deleted so `num_participants` and `num_voters` has to be used instead.

**Comment by Steditor** [comment]
Oh, true. I thought they were private, as other Schülerklub evaluations sometimes are - but you're right: the common theme is the set of external participants.
