### ISSUE TITLE
Course details should be accessible read-only for student representatives in all stages

### ISSUE THREAD

**Issue by cyroxx** [fsr-itse/EvaP#133]
At the moment, for courses which are in one of the states "evaluated", "reviewed" or "published", student representatives cannot see the details (like lecturer, participants, and so on) of this course.

It is true that the details of a course MUST NOT be edited in those states. However, it is desirable to have read-only access to this information e.g. to check the list of lecturers and to identify potential permission issues arising from it ("X is proxy of Y, but why can't X access Y's course results? Is Y really the main lecturer [='Dozent' flag]?)

**Comment by janno42** [comment]
#505 adds archiving functionality. in archived semesters all courses should get a link to open them in read-only mode.

**Comment by karyon** [comment]
@Nef10 do you still want to do this or should i remove your assignment?

**Comment by Nef10** [comment]
You can remove my assignment

**Comment by janno42** [comment]
in the meantime all courses that are not in the state `published` can already be opened. so this change is only necessary for this last state.

**Comment by kateyy** [comment]
Pls assign me =)
