### ISSUE TITLE
Add a "per lecturer todo" view

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#137]
Thomas Schulz created a table which looked like this

- Lecturer 1, Delegates: A, B
       - Lecture 1: status
       - Lecture 2: status

- Lecturer 2 and so on.

which obviously is quite helpful for knowing which lecturer needs a friendly reminder to approve his lectures.

**Comment by Nef10** [comment]
show only prepared courses, but if a course of a lecture who still has prepared courses is already approved, this approved course should also be shown together with the delegate who approved this
