### ISSUE TITLE
"View as" functionality

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#154]
The systems needs a "view as" functionality to allow student representatives to have the exact same views as specific lecturers or students.

**Comment by karyon** [comment]
there are dango packages for this, https://github.com/arteria/django-hijack seems pretty suitable. there seems to be very little glue code needed.

**Comment by janno42** [comment]
django-hijack was successfully used for https://github.com/fsr-itse/1327 so this would be the library to use here as well.

**Comment by karyon** [comment]
see https://github.com/fsr-itse/1327/pull/382 and https://github.com/fsr-itse/1327/pull/417

**Comment by janno42** [comment]
this feature is not needed because staff users should usually know how the views for all user groups work and look like and in extreme cases there is always an admin of the platform with access to a testing instance who can reconstruct the issue.
