### ISSUE TITLE
UI Design issues

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#218]
this issue is meant to be more of a meta-issue, feel free to add more issues in comments or in the list.
- when using the search function in datables, it makes the page (primarily the results page) move as the table may get smaller which can cause the page to scroll up. this can be confusing. see #369 for details.

**Comment by janno42** [comment]
(see #491) The head of table shown on the questionnare overview page is not correctly aligned to the table body. see the attached image
![wrong_align](https://cloud.githubusercontent.com/assets/2399349/5766184/c3364804-9cff-11e4-84a1-976918948fab.png)

**Comment by janno42** [comment]
The light gray rows on the voting page (and maybe other places) have a white rectangle when the line gets too high. it's slightly visible under the vote buttons in the image below:
![capture](https://cloud.githubusercontent.com/assets/1781719/5884524/1d32e9d8-a35f-11e4-89d9-6ff9c82cb88a.PNG)

**Comment by janno42** [comment]
if warnings have more than one line of text the close button is displayed too far on the bottom. it should be on the height of the first line of text.
![error message](https://cloud.githubusercontent.com/assets/1781719/5884528/422bd0d8-a35f-11e4-85a8-822ede21d3cd.PNG)

**Comment by janno42** [comment]
when displaying the platform in german the action buttons don't fit in one line and have no margin between the two rows:

![actions](https://cloud.githubusercontent.com/assets/1781719/6881140/f5f11c16-d552-11e4-8e6a-28b7417152d2.PNG)

**Comment by janno42** [comment]
The questionnaire tooltips are too wide for smaller screens:
![untitled](https://cloud.githubusercontent.com/assets/1781719/7349266/1d799292-ecf8-11e4-8ad3-162d2301e469.png)

**Comment by karyon** [comment]
![2015 05 07 19_17_08-000036](https://cloud.githubusercontent.com/assets/1891915/7521464/3bd88326-f4ee-11e4-94e4-e84f7f14ebf3.png)
see screenshot. this is in staff_questionnaire_form.html. @janno42, could you fix this?

**Comment by janno42** [comment]
The result pages must show the semester name. Currently this name is only visible in the breadcrumbs, which are not displayed for students.

**Comment by karyon** [comment]
lets discuss whether there will ever be a solution for this.

**Comment by janno42** [comment]
jumping tables are not really a big problem. a possible solution would be adding one screen size of invisible content behind the last table resulting in enough whitespace at the end of the page to prevent unintended scrolling. on the downside the user would then have "useless" whitespace and could scroll into nothingness. we decided to to nothing about it.
