### ISSUE TITLE
export is unclear and too large

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#303]
the export is pretty huge, unhandy to use and a bit unclear.

ideas to improve that:
 * omit questionnaires that have no answer in none of the courses.
 * add thicker horizontal lines between questionnaires to lead the user faster from a grade to its question.
 * put different types of courses on separate pages. e.g. one page for lectures, one for seminars, one for the rest. if we can agree on putting different questionnaires on each page, this would allow for even less questionnaires on page and less vertical eye traveling so to say.

**Comment by janno42** [comment]
Exports can now be separated into mulille sheets, each holding a selection of course types. That makes the exported tables much smaller.
