### ISSUE TITLE
Compare a course's results over time

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#313]
It would be nice to see how the results for a repeatedly taught course changed from year to year.
- This requires some kind of course matcher which can find similar courses in different semesters.
  - since there are seminars that change name but not content, there might be user interaction required for this.
- this might make the platform somewhat more unofficial since it might not always be perfectly clear whether some course is the predecessor of some other course.
  - for example, what about courses that change the lecturer like in TI?
- also, this might be a bit unfair since lecturers may change their concept in response to bad grades

**Comment by karyon** [comment]
keep in mind that there are master seminars who change name but not content, so there might be user interaction necessary to match those.

**Comment by janno42** [comment]
- staff an lecturers should be able to see a timeline comparing a course's results over multiple semesters
- this timeline would list courses under each other and have the total grades next to each other in a matrix with respective color coding
- it's not clear whether that view should be accessible to students

- courses would need to be assigned to a "series" or similar, mapping t.b.d.

**Comment by janno42** [comment]
this will be partly implemented in #571 (filtering for a certain course name).

other course series grouping features are not planned. this issue remains open for a contributor-specific comparison feature of own courses over time.

**Comment by janno42** [comment]
related to #1218

**Comment by janno42** [comment]
obsoleted by #571 and #1218
