### ISSUE TITLE
Search field for contributor selection

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#346]
The current contributor selection is a simple dropdown list with all users. Therefore you can only search for people when starting to type their first name.
This should be changed so that the dropdown is replaced by an edit field that has a dropdown option which can be manually triggered and that opens automatically when starting to type and which then only holds names that contain the typed substring (like the multiselect input alread does).

**Comment by lawrencebenson** [comment]
assign me

**Comment by janno42** [comment]
@lawrencebenson please accept github group invitation
