### ISSUE TITLE
PDF export for course results

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#392]
We need an option to export the results of a course as a PDF document.
This should be available for staff users and responsible contributors.

**Comment by karyon** [comment]
server-side pdf rendering would probably either use headless chrome or phantomjs, which is webkit-based. the resulting pdf will probably not differ from chrome's save-to-pdf functionality we use today.

in firefox, the output isn't as pretty yet (see #1013). additionally, firefox doesn't support pdf rendering, one would need to use a pdf printer, resulting in larger filesizes.

so, advantages of server-side pdf rendering would be:
* users save some clicks
* users don't need to use chrome (partly addressed in #1013)

disadvantages:
* implementation effort
* additional infrastructure complexity that adds maintenance burden
* less flexibility (we loose the options in the printing dialog)

we decided it's not worth it.
