### ISSUE TITLE
All contributors should get "My courses" page

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#432]
Currently only editors can see the contributor overview page with all their courses. This should be enabled for all contributors.

On this page users should have different options per course based on their role in this course and the current state:
- Editors (and their delegates):
  - when the course is ```prepared```: they have an edit and a preview option
  - when the course is between ```lecturerApproved``` and ```reviewed``` : they have a view button linking to the read only edit page and a preview option
  - when the course is ```published```: they have a button linking to the course's results
- Contributors who are not editors:
  - when the course is between ```prepared``` and ```reviewed``` : they have a preview option
  - when the course is ```published```: they have a button linking to the course's results

**Comment by lmm-git** [comment]
please assign me, thanks!
