### ISSUE TITLE
Users x.y and x.y2 are both shown as "X Y" in the UI

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#447]
Currently, when there are two users with the same first name and last name, they will have different usernames (usually by appending a number to the newer user), but they will be shown as "Firstname Lastname" in all the lists in the EvaP UI, making them indistinguishable. 

@janno42 and I think the best solution in terms of code and UI simplicity is to add this number also to the last name of the respective user. This needs to be done on production.

The actual todo for this issue is to add a warning in the importer when a new user with the same first and last name as an existing user is about to be added.

**Comment by WGierke** [comment]
Ich würde mich mal ransetzen wollen :)
