### ISSUE TITLE
Exclude questions for external contributors

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#462]
It should be possible to exclude questions like "was available even outside the course" inside a lecturer questionnaire for external contributors.
The questionnaire could then be the same for all lecturers, but wouldn't hold this question if asked about an external person.

**Comment by karyon** [comment]
#457 probably makes this a lot easier to implement.

**Comment by karyon** [comment]
we couldn't think of more questions that would need this feature, and even the question above is relatively fair to ask for external contributors. so right now we don't see any real benefit for this feature.
