### ISSUE TITLE
Unhandled error while importing data (student with different email)

### ISSUE THREAD

**Issue by numberpi** [fsr-itse/EvaP#471]
If the import data contains rows with same student name but different email:

![screenshot](https://cloud.githubusercontent.com/assets/4451364/5761870/9a91ef1e-9cde-11e4-9573-907d949f2b0e.png)

causes the following error:

![screenshot](https://cloud.githubusercontent.com/assets/4451364/5761949/33a0fc90-9cdf-11e4-867c-f046051c6242.png)

**Comment by WGierke** [comment]
assign me pls
