### ISSUE TITLE
calculate results upon publishing, cache indefinitely

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#475]
currently, results are calculated when a user wants to view them, and they are cached for one day. that means a lot of people will need to wait ~10s for the results.

**Comment by janno42** [comment]
the result preview page should not use the cache.

**Comment by karyon** [comment]
if e.g. a comment slipped through review and we have to remove it after publishing, we'll have to clear the cache for the respective course. do we want to account for that in code?

**Comment by janno42** [comment]
maybe we could add an option "refresh cache" which would delete all cached results for a semester and recalculates everything?
