### ISSUE TITLE
Redirection loop on some 403 errors

### ISSUE THREAD

**Issue by lmm-git** [fsr-itse/EvaP#483]
Steps to reproduce:
* Login as sample contributor
* Call a function you have no rights to like [http://localhost:8000/contributor/course/1499/edit](http://localhost:8000/contributor/course/1499/edit)
* You will get an redirection loop

Can someone verify it?

**Comment by WGierke** [comment]
pls assign @lawrencebenson and me

**Comment by WGierke** [comment]
contributors/views.py course_edit is only executed if @editor_or_delegate_required succieds. That method proofs if the user is edit or delegator. Because that's not the case he is redirected to the login page with the next param set to the course edit page. The user is already authenticated so he is redirected back again to the course edit page.

**Comment by karyon** [comment]
fwiw, i found this in an old commit:
```
def user_passes_test_without_redirect(test_func):
    """
    Decorator for views that checks that the user passes the given test.
    The test should be a callable that takes the user object and returns
    True if the user passes.
    """

    def decorator(view_func):
        @wraps(view_func, assigned=available_attrs(view_func))
        def _wrapped_view(request, *args, **kwargs):
            if test_func(request.user):
                return view_func(request, *args, **kwargs)
            raise PermissionDenied
        return _wrapped_view
    return decorator

```
i removed it because it was unused. this is not the complete solution, it does not redirect to login URL if the user is not authenticated.

**Comment by karyon** [comment]
@WGierke, @lawrencebenson, do you still want to have a look at this? otherwise i'm probably the one who has to do this :)

**Comment by lawrencebenson** [comment]
if you are at it already, feel free to take over
