### ISSUE TITLE
Make usage of Font consistent across platforms

### ISSUE THREAD

**Issue by Bartzi** [fsr-itse/EvaP#495]
Different operating systems use different fonts and therefore certain layout errors as seen below may occur. The task is to investigate whether this is actually the case.
If this is the problem we need to make sure that every client uses the same font!

![image](https://cloud.githubusercontent.com/assets/2399349/5784538/27fe4c1e-9dcd-11e4-945b-412e87e46e5f.png)

**Comment by karyon** [comment]
using the same font might be sufficient, but in theory this could still occur since this is also dependent on font rendering. we could also hack this by adding a few px to the page/button area width or making the font or margins inside buttons a bit smaller.

**Comment by karyon** [comment]
@janno42 says it should be possible to first render the buttons and then let the question column take up the remaining space.

**Comment by janno42** [comment]
issue shown above is fixed. we decided against sending a font. other occurrences will be solved case by case. a general solution will be flexboxes in Bootstrap 4.
