### ISSUE TITLE
Contributors can change responsibles

### ISSUE THREAD

**Issue by lmm-git** [fsr-itse/EvaP#504]
I think I found a little (not very important) security issue: contributors can change the person who is responsible by changing the hidden input field.

To reproduce:
* Be sure that the user contributor has a valid course which he can edit
* Login as contributor
* Go to the edit page of the course
* Change the hidden field value with id ```id_contributions-X-contributor``` (x is typically 0) to a valid user id like 477
* Save the course
* Now has the course a new rsponsible...

**Comment by janno42** [comment]
Possible solution: When cleaning the form, the value for the responsible contributor should always be set to its original value.
