### ISSUE TITLE
Save and approve for staff

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#506]
The course edit view for staff users should get a ```Save and approve``` button just like the contributors' page which moves the course into the ```approved``` state.

**Comment by karyon** [comment]
should this appear for lecturerApproved courses, or also for new and prepared ones, allowing to skip the responsible altogether? this might happen accidentally.

**Comment by janno42** [comment]
the button should be visible in all states before `approved`, but a warning should be displayed above it if the editor didn't approve the course yet.
