### ISSUE TITLE
Menu bar hides content

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#512]
The navigation on top of the page hides parts of the content if its size increases. This happens in smaller browser windows, where the navigation bar has more than one line but is not yet compressed into a single icon.
The content should always be visible.

![capture](https://cloud.githubusercontent.com/assets/1781719/5887235/763386a4-a3c4-11e4-8b93-c2999d8ca74a.PNG)

**Comment by karyon** [comment]
reopening. we opted to fix #641 instead of this one here. right now i don't know of a good solution that fixes both issues, apart from making the navbar static instead of fixed to top, which we didn't want.

maybe bootstrap 4 fixes it :)
