### ISSUE TITLE
Documentation Build failed

### ISSUE THREAD

**Issue by cyroxx** [fsr-itse/EvaP#517]
Due to the latest commit (12f21ff937bd9702cfdcc806e1122ad90c213940), the build at ReadTheDocs failed: https://readthedocs.org/builds/evap/2252334/

**Comment by janno42** [comment]
Thanks for letting us know.
On this occasion I'm hereby voting for not using Read the Docs anymore and instead moving all documentation into the GitHub Wiki. We would then have everything at one place.

**Comment by cyroxx** [comment]
This was an easy fix. I just changed the Python interpreter to "CPython 3.x" in the admin panel of the RTFD project.

I would suggest to close this issue now and discuss the "Should we use RTFD anymore at all?" in a different one.

**Comment by janno42** [comment]
check. could you give me the rights to edit the rtd settings by myself?

**Comment by cyroxx** [comment]
I can do that, but you would need to register there first. So far, I get the message: "User janno42 does not exist".

**Comment by janno42** [comment]
Okay, please try again :)

**Comment by cyroxx** [comment]
Done. You're added to the RTFD project as a maintainer now. Use your force wisely ;)

**Comment by janno42** [comment]
thanks
