### ISSUE TITLE
ToolTip's position is dependent on scroll position

### ISSUE THREAD

**Issue by Steditor** [fsr-itse/EvaP#535]
The further you scroll down, the further the tooltip is displaced from the event origin.
E.g.: https://evap.hpi.de/results/semester/20/course/1779
![evap-tooltips](https://cloud.githubusercontent.com/assets/2188983/6778337/252572e8-d152-11e4-9ccf-eac6a0c1f1a4.png)

**Comment by janno42** [comment]
occurs in current firefox version, no problem in chrome.
