### ISSUE TITLE
Clean up jumping to content

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#539]
The FAQ and the comments page make use of jumping to specific elements by using fragment identifiers in the URL.
Because the navbar hides some content in the topmost 50 px, this currently involves JavaScript which scrolls the page after some timeout. The timeout is needed, because Chrome doesn't seem to scroll otherwise.
The code used for this workaround should be cleaned up.

**Comment by karyon** [comment]
please also deal with #512.
