### ISSUE TITLE
when viewing a evaluated lecture as tutor, no results are shown

### ISSUE THREAD

**Issue by LanDinh** [fsr-itse/EvaP#544]
"Mod I" is evaluated (I was tutor) and there is a "Vorschau" button, but when I click it, the screen looks just like a lecture that I can evaluate, I can mark options and give grades etc., but at the very bottom, there is only a "Zurück" button, and I don't see the results.

**Comment by janno42** [comment]
@LanDinh: Please don't create tickets for such requests. Could you please send us a short message to our hpi email address so we know whom to answer?
