### ISSUE TITLE
collapse contributors with no answers in course detail pages

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#555]
Contributors who didn't get any answers should be collapsed on the results pages, so that the empty answer lines are not shown.
This should also happen if there are answers in the database, but none of them can be seen by the current user.

![2015 04 02 17_37_57-000018](https://cloud.githubusercontent.com/assets/1891915/6967376/2b406e48-d95f-11e4-99da-37d2f04ec3e1.png)

**Comment by karyon** [comment]
there is some code which should remove those lines: https://github.com/fsr-itse/EvaP/blob/839ef21a8dfaec7c0e8a51fda4e0c1bdd9c8376d/evap/results/views.py#L96 but it does not work, as there is a result (and not None or the like) for each question even if it has no answers.

besides, we don't want to remove those questions, but rather collapse a questionnaire (or "section" as it's called in that part of the code) if none of it's questions has answers.

**Comment by schumannd** [comment]
Tho code in question would make the whole section disappear. The sections are currently not collapsable. So one solution would be changing the layout of all results pages to include collapsible Sections.
