### ISSUE TITLE
rewrite anonymizer in python

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#556]
this should result in a lot less complexity in there. maybe make it a management command.

**Comment by cyroxx** [comment]
If you make this a management command, please require the user to confim the anonymization run.

Something along these lines:

> DANGER!
> This action will result in IRREPAIRABLE DATA LOSS!
> Is this really what you want? If so, type "yes"

or any of those standard confiirmation questions.

**Comment by karyon** [comment]
no worries, i'm even thinking about asking this twice or not allowing it with DEBUG=False.

**Comment by cyroxx** [comment]
Good. I was also thinking about the DEBUG switch actually.

**Comment by karyon** [comment]
@cyroxx, in the PR I went with asking twice if DEBUG is false, once otherwise.
