### ISSUE TITLE
Warning if email address is missing when sending emails for course

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#596]
When sending emails for a course (e.g. when publishing it), a warning must be shown if the email address is missing for a user to whom an email should be sent.
This can be a Django warning in the UI when sending the emails was triggered by a staff user, but must be handled differently when the situation occurrs when a cronjob triggers it. Maybe a message should be send to the admins.

**Comment by karyon** [comment]
all mail is sent through EmailTemplate.__send_to_user(). So, the plan would be to find out whether a user is logged in or a cronjob triggered the email sending, and then, in that method, either send an email to the admins or display a django message for each missing email address. the existing handling in staff.views.course_email can probably be removed then.

**Comment by janno42** [comment]
in `__send_to_user` an error email should be sent to the admins if no email address for the requested user exists. this should happen in all cases, whether sending was triggered by a user or cronjob.
`logger.error` should do the trick, but is not working for some reason.
