### ISSUE TITLE
Number of voters is not handled correctly

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#601]
#598 causes that the number of voters is not always handled correctly. that happens e.g. on the results page as shown on the screenshot below:
![voters](https://cloud.githubusercontent.com/assets/1781719/8271597/3de7c53c-1820-11e5-9541-f28f95733fa5.PNG)

this also prevents students from accessing the results pages, they see the message "Not enough answers were given". the results are still displayed when accessing the results page as a staff user (again, the overview pane states that there have been 0 voters). the number of voters on the semester managing page is correct and no warning "Not enough questionnaires assigned" is displayed there.

**Comment by janno42** [comment]
the problem was actually caused by cc4e7c6c3bedc525903919bf51a7badfcde911a1, changing the `related_name`of `last_modified_user` of `GradeDocument` prevents it.
the reason is not clear yet.

**Comment by karyon** [comment]
i opened https://code.djangoproject.com/ticket/25027 for this.
