### ISSUE TITLE
Translation of Grade Documents

### ISSUE THREAD

**Issue by Nef10** [fsr-itse/EvaP#623]

**Comment by janno42** [comment]
Could you please be so kind and give us a short problem description? :)

**Comment by Nef10** [comment]
missing translation 
<img width="616" alt="screenshot 2015-09-07 12 57 39" src="https://cloud.githubusercontent.com/assets/4551135/9715417/266eace0-5560-11e5-8628-e3c8f406807a.png">

**Comment by janno42** [comment]
In the dropdown menu where students can download their grades the name of the document is not translated, beacuse it's a name that the Studienreferat enters. The respective field is getting a default entry "Endnoten" in case they don't put a different name there. So there is no translation yet.

**Comment by Paul-Geppert** [comment]
Please assign me to this ticket. My suggestion is the same as janno42 has ("We could allow entering two names (German and English) to have a translation.").
I'm also assigned to the issue #628, which needs the solution of this issue.

**Comment by janno42** [comment]
fixed in #666
