### ISSUE TITLE
Archive grade documents

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#633]
It should be possible to archive grade documents after a certain time. Archived grade documents should then not be available for download anymore.
This could be connected to archiving semesters.

**Comment by karyon** [comment]
maybe we could restrict downloading of grades to the courses one participated in.

**Comment by janno42** [comment]
In case we want to do that we have to make sure that the enrollment is always up to date. Currently changes after the initial import are not reflected in our database.
To do that we could give the Studienreferat a place where they can change a user's participations by themselves which means more work for them.

**Comment by karyon** [comment]
ignore the last two comments, we won't do that. simply disabling download when a semester is archived should be enough.

**Comment by janno42** [comment]
Archiving grade documents should be possible even before archiving a semester.
*Preferred solution:* Staff users should be able to disable downloading grade documents in the semester options.
