### ISSUE TITLE
Make selection of responsible a radiobutton

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#637]
when editing a course, the red part (see screenshot) should be a radiobutton, because there must be exactly one responsible person.

![2015_09_20_16_22_02](https://cloud.githubusercontent.com/assets/1891915/9981125/1612f578-5fb4-11e5-9455-4a74f085c024.png)

**Comment by karyon** [comment]
@janno42 mentioned there was some kind of problem back then when creating the page. maybe it's this here: https://github.com/elo80ka/django-dynamic-formset/issues/81

**Comment by janno42** [comment]
not needed anymore after #643
