### ISSUE TITLE
Menu bar completely empty if the window is not very wide

### ISSUE THREAD

**Issue by j4yk** [fsr-itse/EvaP#647]
All options in the menu hide in the "responsive" drop down at a width of 1280px, even though there would be plenty of space to show at least My Courses (student) which is what I want to navigate to on 99% of my visits.

![image](https://cloud.githubusercontent.com/assets/151175/10396239/b98b4fc4-6ea1-11e5-9e5c-18645441ecd6.png)

![image](https://cloud.githubusercontent.com/assets/151175/10396300/171dbb68-6ea2-11e5-9fb6-4f0f3489bdd4.png)

Actually, the minimum size which has the items appear in the bar features some (seemingly wasted) blank space:

![image](https://cloud.githubusercontent.com/assets/151175/10396366/6e077324-6ea2-11e5-8cb0-df1fa81af6dd.png)

**Comment by karyon** [comment]
yeah, i'm annoyed by that as well. i introduced it in an attempt to fix the navbar for staff users who have a lot more menu items (see https://github.com/karyon/EvaP/commit/531adb4cc5a2b31af26bb814c715a2a344e4338e), but at that time wasn't aware that it would worsen the situation for all the students.

thanks for the push, i'll look into it this weekend and either find a solution that works for both user groups, or, if i'll find that it's too complicated, revert that commit.

dup of #641.
