### ISSUE TITLE
Force line breaks in comments

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#650]
When posting a link into a comment, it might get too long for the page and breaks the layout.
![linebreak](https://cloud.githubusercontent.com/assets/1781719/10610596/db2d6c20-7748-11e5-80c3-5d645b2234b9.PNG)

Line breaks should be forced.

**Comment by dietzi96** [comment]
assign me please

**Comment by janno42** [comment]
fixed in e17fa26fdf2abdbbd9c349988f949a7b995bf8a1
