### ISSUE TITLE
Overview per degree on staff pages

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#671]
The statistical overview on top of the staff's semester pages should not only show the total values, but also the values per degree.
A table with one line per degree and a total line is suggested. Also the panel should be collapsible like contributor questionnaires on the student's evaluating pages. Whether or not the panel is shown in a collapsed state should be saved in a similar way as the decision whether reviewed comments are displayed on the comment review pages.

Current overview:
![overview](https://cloud.githubusercontent.com/assets/1781719/11336196/8195148c-91e3-11e5-8c30-c96ae6479656.PNG)

**Comment by karyon** [comment]
@simonkrogmann just noticed you have a branch open that looks like this issue. if you don't actually plan on implementing this, let me know and i'll remove the assignment :)
