### ISSUE TITLE
Separate importer warnings

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#678]
The importer warning when user data changes should be separated into different groups of warnings. One for each of the following:
- username changed
- name changed
- email changed

Each of these warning groups should be collapsible.

**Comment by He3lixxx** [comment]
Working on this, also including changing the import functionality to a 2-stage process where you first have to upload and test a file in the first stage which can be imported in the second stage then. This currently has functionality / layout collisions with #824, see my comment there.

**Comment by janno42** [comment]
#898 will add another importer which allows to upload a file to add contributors to a course or to copy them from another course.
so we should go for a 2x2 layout, almost like the `contributor/settings` page with two separate rows (one to add participants, one to add contributors) and in each have two options next to each other (one for uploading a file, one for copying users from another course).
