### ISSUE TITLE
Test management commands

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#704]
Because in three years, run_tasks will silently fail on the production system and nobody will notice.

* [x] **run_tasks** - shouldn't be too hard and is rather important
* [x] **anonymize** - might be a bit of work to cover it properly, but should be straightforward.
* [x] **refresh_results_cache** - should be easy
* [x] **dump_testdata** - don't know how not to overwrite the file during testing, but should be possible

the other commands are already tested or rather unsuitable for testing
* [x] **merge_users** - already has a test (#703) and is shown to be pretty broken.
* [x] **run** - don't know how to test this and there isn't really anything that could break. still, somehow running it to check that it doesn't crash right away on e.g. imports would be cool
* [x] **reload_testdata** - don't know whether it's possible at all to test that, i mean it drops the whole database...
* [ ] **import_ad** - we never used it and i don't know whether it's feasible to mock ldap

use `self.stdout.write` instead of `print` and `call_command("command_name", stdout=StringIO())` to avoid console output during tests. don't know what to do about calls to `input`.

**Comment by schumannd** [comment]
calls to input can be mocked as usual:
```
from mock import patch

with patch('builtins.input') as mock_input:
    # do stuff
```
