### ISSUE TITLE
single results not sortable by result

### ISSUE THREAD

**Issue by Nef10** [fsr-itse/EvaP#743]
On the results site of a semester are the single results not sortable by the result. When clicking on the results table header the results get sorted by something, but not the result.

**Comment by schumannd** [comment]
What exactly is meant by "sortable by the result"? I see no results table header on the semester results site.

![screen shot 2016-02-29 at 7 24 43 pm](https://cloud.githubusercontent.com/assets/5385472/13404511/329aa7aa-df1a-11e5-9662-d29ccc029b3a.png)

**Comment by Nef10** [comment]
your screenshot does not show the single results, but the normal course results

**Comment by janno42** [comment]
works in english, but not in german

**Comment by janno42** [comment]
see https://datatables.net/examples/basic_init/comma-decimal.html

**Comment by karyon** [comment]
seems like there is no easy way to get the separator. easiest i found is
```
from django.utils import formats
formats.get_format('DECIMAL_SEPARATOR', formats.get_language(), use_l10n=True)
```

**Comment by karyon** [comment]
a bit easier
```
from django.contrib.humanize.templatetags.humanize import intcomma
intcomma(0.0, True)[1]
```
i'll see whether the IRC knows something non-hacky.
