### ISSUE TITLE
Decide on standard procedure for new css/js code and cleanup evap.css

### ISSUE THREAD

**Issue by schumannd** [fsr-itse/EvaP#752]
evap.css is currently the css rule dump. We should think of a structure for organizing css code. Maybe inline js code as well?

**Comment by karyon** [comment]
you mean moving js code into files? i think most of it contains some template tags so they can't go into the static directory. adding a separate .js file per template file that currently contains js code seems to have little value to me. what do you think?

as for css code, could you describe what is actually bothering you and how a different structure would solve that? i have little clue what's in there so this might help me.

**Comment by schumannd** [comment]
just splitting it up into maybe base styles, hacks/fixes, and other styles would help a bit I think. And maybe putting all js in one file, or multiple files. Just not in the html templates

**Comment by janno42** [comment]
CSSS postponed until change to Bootstrap 4

**Comment by karyon** [comment]
CSS restructuring will happen whenever bootstrap 4 gets released, we update to it and start using SASS. JS code will stay as it is for now, as there is little practical advantage for moving it into separate files.
