### ISSUE TITLE
Find alternative to lastform() method used in many tests.

### ISSUE THREAD

**Issue by schumannd** [fsr-itse/EvaP#754]
While trying to implement a feedback form in the base.html file I broke about 1/3 of all tests:

Some 35 test rely on using lastform() to identify the last form in the page. This breaks when any forms are added at the bottom of the page.
If I add a form to the top, about 15 other tests break. They rely on the form to be tested to be at a certain index.

A fix would be to name all forms and call them by their identifiers instead of relying on their location.

**Comment by janno42** [comment]
I would very much appreciate naming all forms.
