### ISSUE TITLE
Possibility to link old versions of courses

### ISSUE THREAD

**Issue by schumannd** [fsr-itse/EvaP#756]
As a Student I have often found myself looking for old evaluations of currently offered courses. Usually I have to ask people who then tell me something along the lines of: "yeah, course X is essentially course Y back in 2012"

This is definitely something to discuss, as these connections are probably not official. Also courses might have changed in response to bad rankings, and old bad scores might not reflect their current quality.

I still think this would be valuable information for new students who don't have the benefit of knowing older students.

This change might be too big or take the platform onto a too unofficial level, so we should discuss this. It would also require currently offered courses to be listed before students enroll in them, which is another big change. As much as I would like to see this feature I can see that it might be problematic.

This has been referenced in by @karyon in #313

**Comment by karyon** [comment]
included some thoughts from here in #313. duplicate, so closing.
