### ISSUE TITLE
Swapping contributors in course edit form fails

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#775]
When you exchange two contributors in the course edit form, it says "a contribution with this contributor already exists"

you can also e.g. replace contributor A by someone who is not yet a contributor, and then replace contributor B by contributor A.

reordering the contribution works, the problem occurs when changing the contributors of the contributions.

**Comment by janno42** [comment]
- have course with contributors A and B (save it)
- change the first contributor to be B
- remove the second contribution (B)
- save the course
- there is now only one contribution for A -> that's wrong ;)

**Comment by karyon** [comment]
fixed.
