### ISSUE TITLE
Responsible contributor must not be removed by staff

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#781]
Currently staff users can remove the responsible contributor from a course in the UI. Saving fails, but there is no easy way to assign another contributor as responsible.
The remove link should not be enabled for the contributor set as responsible.

**Comment by karyon** [comment]
probably this requires to remove the "delete" link with javascript, depending on which contributor is selected as responsible. if that is implemented, one can probably remove the template code that removes that link on the contributor page.
