### ISSUE TITLE
Remove passwords from error messages

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#792]
EvaP sends error messages to the admins when a server error occurs. Post data sent to the page where the error occurred will be included in the message, but passwords must not be included in these messages.
This currently happens e.g. when a user is logging in who has two accounts like described in #791.

**Comment by karyon** [comment]
for the record, this already happened once two years ago here https://github.com/fsr-itse/EvaP/issues/237 and apparently was not solved completely.
