### ISSUE TITLE
Add times to evaluation period

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#812]
The evaluation period could be defined by days and time instead of just days like currently implemented. That would allow to configure a precisely timed start/end for the evaluation period.

For this, the cron job checking for the start of an evaluation has to run every minute and the documentation must be updated accordingly.

**Comment by tomkellog** [comment]
pls assign

**Comment by tomkellog** [comment]
@karyon

**Comment by karyon** [comment]
Hey, do you plan to continue working on this? otherwise, if you think you won't do this in the next, say, two months, could you push your code so others can pick this up?

**Comment by karyon** [comment]
unassigning @tomkellog at his request. if anyone wants continuing this, #944 is a good starting point. next step would be fixing the test failures and to getting UI feedback from @janno42.

**Comment by janno42** [comment]
The evaluation start should be defined with date and time, the end will be configured with only a date. An entry in the settings should specify an offset that will be added to the evaluation end date (e.g. "03:00", so that if the end date is 01.01., the evaluation will not end at 01.01. 23:59 but actually at 02.01. 03:00.).
