### ISSUE TITLE
Write the due date for confirmation directly into the subject of the e-mail.

### ISSUE THREAD

**Issue by xasetl** [fsr-itse/EvaP#839]
As a lecturer I want to see the due date for preparation of the evaluation directly in my inbox.
step 1: write it into the subject
step 2: send an event invite via e-mail

**Comment by karyon** [comment]
a possible solution would look like this:
* when selecting courses in the staff semester view and clicking "approve", the approval page does not just have yes/cancel buttons but also provides a date input field
* this date is passed as parameter into the email template

however, @janno42 and I think the benefit is probably small to nonexistent, and the implementation work plus the overhead of choosing such a date whenever approving courses is probably not worth it, therefore closing.
