### ISSUE TITLE
Save language settings in profile instead of session

### ISSUE THREAD

**Issue by arneboockmeyer** [fsr-itse/EvaP#859]
I have an US MacBook with an English OS and Evap detects my language (correctly). But I like to read the feedback in german, so I have to switch my language every time when I log in.
It would be great, if this setting could be stored in my profile.

**Comment by karyon** [comment]
ref #391

**Comment by karyon** [comment]
@arneboockmeyer do you logout or clear cookies or something like that after using evap? because theoretically the session should be valid a few months. of course you are free to logout whenever you want to :) i'm just asking to verify i'm understanding this correctly.

**Comment by arneboockmeyer** [comment]
Hm. You might be correct. I think, I logged out. Currently I have an active session (and I logged in a few weeks ago)
