### ISSUE TITLE
Django 1.10 upgrade

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#861]
I have a branch open where all tests are passing and all deprecations are fixed, but the UI is not tested yet and there are some cool new features we might make use of.

Release notes of interest from https://docs.djangoproject.com/en/1.10/releases/1.10/:
- Required form fields now have the required HTML attribute. Set the new Form.use_required_attribute attribute to False to disable it. The required attribute isn’t included on forms of formsets because the browser validation may not be correct when adding and deleting formsets.
- Required form fields now have the required HTML attribute. Set the Form.use_required_attribute attribute to False to disable it. You could also add the novalidate attribute to `<form>` if you don’t want browser validation.
- [since the html required attribute does not work well with the fixed bootstrap navbar, we might need to disable it for every single field which is dumb. the global setting does not work, see https://github.com/dyve/django-bootstrap3/issues/325, so we might need to wait for https://github.com/dyve/django-bootstrap3/issues/337]
- Added the is and is not comparison operators to the if tag.
- Request and response handling of the runserver command is sent to the django.server logger instead of to sys.stderr. If you disable Django’s logging configuration or override it with your own, you’ll need to add the appropriate logging configuration if you want to see that output:

ref https://github.com/django-webtest/django-webtest/pull/56

**Comment by dyve** [comment]
Hi @karyon, I would really like your opinion on

- https://github.com/dyve/django-bootstrap3/issues/337
- https://github.com/dyve/django-bootstrap3/issues/345

So far there has been little response, it looks like you (like me) are at least using these attributes in a living application.

**Comment by karyon** [comment]
@dyve sorry, we haven't used the django-bootstrap3 options, just the django ones. in the paragraph in the original post above i've been confused apparently, the way i see it now the problem has nothing to do with django-bootstrap3. it's caused by django (since it now renders the required attribute) and can be solved with django (by setting `Form.use_required_attribute` to False on every form).

so i think this project here isn't concerned what django-bootstrap does with that option. personally, i agree that duplicating django's functionality is confusing. django also has an option to disable rendering the required attribute [for forms](https://docs.djangoproject.com/en/1.10/ref/forms/api/#django.forms.Form.use_required_attribute) and even for [single widgets](https://github.com/django/django/pull/7419), so i'd say there is no intuitive way how the `set_required` global option of django-bootstrap should work, and overriding this when rendering widgets is nice to have but not essential. i'm not sure about rendering the disabled attribute, which cannot be configured with django. but i won't complain if you leave that removed as well.

**Comment by dyve** [comment]
Thanks for your reply @karyon.
