### ISSUE TITLE
Buggy 'required' tooltip placement

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#916]
The html5 required (used since https://github.com/fsr-itse/EvaP/commit/402c7002ac516028f7fb9bfb9dabf78c62dbe90a) field does not work correctly with some form fields.

To reproduce: open the course create page (staff/semester/x/course/create), enter a german and english name, and save. now enter a course type and save. both times the tooltip will be in the wrong place. tested with chrome and firefox.

![2017-02-07 11_19_12-settings](https://cloud.githubusercontent.com/assets/1891915/22687280/9cb5d620-ed27-11e6-8791-95a43bcefa51.png)

![2017-02-07 11_19_29-settings](https://cloud.githubusercontent.com/assets/1891915/22687285/a06c6310-ed27-11e6-9610-00c8b0b19197.png)

**Comment by janno42** [comment]
see https://github.com/fsr-itse/EvaP/pull/1005#issuecomment-325945257
