### ISSUE TITLE
Inactive users

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#950]
Users should get an additional attribute, stating whether they are active or not (default: active).
The bulk deletion should get an additional option, that all users who would be deleted but can't (because they are participating in or contributing to a non-archived course or delegates or cc users of such users) will be marked inactive instead.

Inactive users are then not to be shown in participant or contributor selection fields, the importer should show a warning if an inactive user will be added to a course and an option should be added to the staff user list, whether inactive users should be shown (if so they will be marked with a respective label).

**Comment by karyon** [comment]
django's AbstractBaseUser, from which our UserProfile inherits, already has an is_active field specifically for this purpose: https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.is_active. we should use that.

we could filter out inactive users by default similar to how we filter out the cronjob user by default: https://github.com/fsr-itse/EvaP/blob/master/evap/evaluation/models.py#L799. The UserProfileManager could get a `include_inactive_users` (possibly taking a boolean parameter if that simplifies things) method, analogue to `with_cronjob_user`.

**Comment by He3lixxx** [comment]
assign please
