### ISSUE TITLE
Importer uses email to identify users, not username

### ISSUE THREAD

**Issue by karyon** [fsr-itse/EvaP#953]
external users don't need to have an email address. however, in at least two places: [1](https://github.com/fsr-itse/EvaP/blob/fd411b811790edb4ee4949591f43608e0531b279/evap/staff/importers.py#L96), 
[2](https://github.com/fsr-itse/EvaP/blob/fd411b811790edb4ee4949591f43608e0531b279/evap/staff/importers.py#L318) we use the email address to identify users. these lines probably crash when the user does not have an address. in another place [3](https://github.com/fsr-itse/EvaP/blob/fd411b811790edb4ee4949591f43608e0531b279/evap/staff/importers.py#L195) the error message won't be helpful at all.

if i'm wrong, it should probably be documented why this is safe :)

**Comment by karyon** [comment]
@He3lixxx this is probably an easy one for you as well.

**Comment by He3lixxx** [comment]
tl,dr: All three cases are similar, in the current code, its always guaranteed that "process_user" is called on the data before the critical line. This sets an error which guarantees that the code line does not execute. There are already tests that test this case for Link 2 and 3. For 1, this is missing currently, but it could be added by editing a fixtures (invalid_enrollment_data.xls - delete one of the responsible's emails and edit the test to check for this error).

Link 1.:
In the class `EnrollmentImporter`:
There is a `UserProfile.objects.get()` with email selector in `CourseData.store_in_database`. The CourseData class is only used in the EnrollmentImporter class in read_one_enrollment which is called in the `process` method with `for_each_row_in_excel_file_do`. This stores the responsible user's data in the `associations` dictionary. The method `consolidate_enrollment_data` is called afterwards in the `process` method, this loops through all items in the `associations` dictionary and calls `process_user`for every entry, including the responsible user's data. This would add an error to the `errors` list if the email was empty, leading to `write_enrollments_to_db` not being called at the end of `process`, so `CourseData.store_in_database` not called in this case.

This is not tested currently, but Link 2 has a very similar situation and there, this case is tested. With editing the invalid_enrollment_data.xls fixture, we could easily make this situation appear in a test.

Link 2.:
This is pretty similar:
In the class `EnrollmentImporter`:
`UserProfile.objects.get` by email in `write_enrollments_to_db` method
email taken from `self.enrollments`
`write_enrollments_to_db` only called from process method if there were no errors before
`consolidate_enrollment_data` was called before in `process` (`enrollments` filled there)
`process_user` was called, this checks for empty emails and throws an error if empty
-> if a user has no email set, `write_enrollments_to_db` will not be called

For this case, a test exists: `TestEnrollmentImporter.test_invalid_file_error`. This tests a file that contains an empty email address for one of the students.

Link 3.:
Also pretty similar:
In the `UserImporter` class:
`UserProfile.objects.get` by email in `check_user_data_correctness`. This is called in two places: `UserImporter.process` and `EnrollmentImporter.process`. Both times `consolidate_enrollment_data` or `consolidate_user_data` is called before. This calls `process_user` which again checks the email and adds an error if there is no email address. So there would be at least one meaningful error ("Email missing") before the line without any useful information ("User ' ': Error ..."). To prevent the useless error, we could add more information to the error message (e.g. the first and last name), but I don't know whether this would be necessary.

There is a test for the meaningful error in `TestUserImporter.test_invalid_file_error`. This tests the error when importing a file that contains an empty email field.
