### ISSUE TITLE
Questionnaire assignment warning for contributors without questionnaires

### ISSUE THREAD

**Issue by janno42** [fsr-itse/EvaP#960]
The label "Not enough questionnaires assigned" is always shown next to courses on the staff page where one of the contributors has the checkbox "Does not contribute to course" selected.
This should count as an assigned questionnaire in respect of this warning message, which should not be displayed if the course has sufficient questionnaires assigned otherwise.

The property `has_enough_questionnaires` must be adapted to reflect this.

**Comment by karyon** [comment]
well, the problem here is that "Does not contribute to course" is not saved anywhere. right now the code simply checks that checkbox if there are no questionnaires selected. Which is probably not what we want in case of newly imported courses...

**Comment by janno42** [comment]
This also prevents approving courses in case a contributor has no questionnaires.

**Comment by karyon** [comment]
as discussed, `has_enough_questionnaires` should simply not care about contributors.

however, when selecting multiple courses in the semester view and approving them, courses that have a contributor with no questionnaires should get a warning in the confirmation page.
