### ISSUE TITLE
Provide a grouping feature for questionnaires

### ISSUE THREAD

**Issue by laurenzse** [fsr-itse/EvaP#975]
In many events the evaluation consists of multiple sections (e.g. General Questions, Food, Contents etc.) leading to many questionnaires cluttering up the staff area. One way to better organize those questionnaires could be a grouping feature, which allows one to hide and seek many questionnaires at the same time.

Currently, we just put all questions in one (long) questionnaire - which makes organizing the different sections hard and also looks unpleasing to the users completing the questionnaire.

**Comment by janno42** [comment]
we need to discuss the connection to #457 and what we actually want to have

**Comment by karyon** [comment]
proposal: introduce a new question type, "heading" or something like that. it obviously won't get any answers. the questionnaire form doesn't need to be changed, the voting pages, results pages, and the export begin a new section of some sort when encountering such a heading question, ideally a level lower than the questionnaire heading. other places, e.g. result calculation, need to filter questions accordingly.

another option would've been: questionnaires can contain questions and other questionnaires. that would be quite a lot more complex, for additional flexibility that we probably don't need.

**Comment by He3lixxx** [comment]
assign please
